
package com.aitequ.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyServiceInterface", targetNamespace = "http://webservice.aitequ.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceInterface {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.aitequ.com/", className = "com.aitequ.webservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.aitequ.com/", className = "com.aitequ.webservice.AddResponse")
    @Action(input = "http://webservice.aitequ.com/MyServiceInterface/addRequest", output = "http://webservice.aitequ.com/MyServiceInterface/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://webservice.aitequ.com/", className = "com.aitequ.webservice.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://webservice.aitequ.com/", className = "com.aitequ.webservice.MinusResponse")
    @Action(input = "http://webservice.aitequ.com/MyServiceInterface/minusRequest", output = "http://webservice.aitequ.com/MyServiceInterface/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
